Use config dir

diff --git a/services/traefik/Makefile b/services/traefik/Makefile
--- a/services/traefik/Makefile
+++ b/services/traefik/Makefile
@@ -51,31 +51,19 @@ up-master: .init .env ${TEMP_COMPOSE}-master ## Deploys the stack on dalco clust
 
 # Helpers -------------------------------------------------
 
-.PHONY: .dyn_cfg.loc
-.dyn_cfg.loc:
-	@if [ ! -f .dyn_cfg.loc ]; then \
-		echo "Error: .dyn_cfg.loc file does not exist." >&2; \
+traefik_dynamic_config.yml: .config.dir
+	$(eval CONFIG_DIR=$(shell cat $(REPO_BASE_DIR)/.config.dir))
+	$(eval TRAEFIK_DYN_CFG=$(CONFIG_DIR)/traefik_dynamic_config.yml)
+	@if [ ! -f $(TRAEFIK_DYN_CFG) ]; then \
+		echo "Error: file does not exist $(TRAEFIK_DYN_CFG)" >&2; \
 		exit 1; \
-	fi
-	@LINE_COUNT=$$(wc -l < .dyn_cfg.loc); \
-	if [ $$LINE_COUNT -ne 1 ]; then \
-		echo "Error: .dyn_cfg.loc must contain exactly one line." >&2; \
-		exit 1; \
-	fi
-	$(eval DYN_CFG_LOCATION=$(shell cat .dyn_cfg.loc))
-	@if [ ! -f $(DYN_CFG_LOCATION) ]; then \
-		echo "Error: The file specified in .dyn_cfg.loc does not exist: $(DYN_CFG_LOCATION)" >&2; \
-		exit 1; \
-	else \
-		echo "Using $(DYN_CFG_LOCATION) dynamic config file."; \
 	fi
 
-dyn_cfg.yml: .dyn_cfg.loc
-	$(eval DYN_CFG_LOCATION=$(shell cat .dyn_cfg.loc))
-	cp $(DYN_CFG_LOCATION) $(shell pwd)/dyn_cfg.yml
+	@cp $(TRAEFIK_DYN_CFG) $(REPO_BASE_DIR)/services/traefik/traefik_dynamic_config.yml
+
 
 .PHONY: ${TEMP_COMPOSE}-local
-${TEMP_COMPOSE}-local: dyn_cfg.yml docker-compose.yml docker-compose.local.yml .env
+${TEMP_COMPOSE}-local: traefik_dynamic_config.yml docker-compose.yml docker-compose.local.yml .env
 	@set -o allexport; \
 	source .env; \
 	set +o allexport; \
@@ -96,28 +84,28 @@ ${TEMP_COMPOSE}-letsencrypt-dns: docker-compose.yml docker-compose.letsencrypt.d
 	${REPO_BASE_DIR}/scripts/docker-compose-config.bash -e .env $< docker-compose.letsencrypt.dns.yml > $@
 
 .PHONY: ${TEMP_COMPOSE}-aws
-${TEMP_COMPOSE}-aws: dyn_cfg.yml docker-compose.yml docker-compose.aws.yml .env
+${TEMP_COMPOSE}-aws: traefik_dynamic_config.yml docker-compose.yml docker-compose.aws.yml .env
 	@set -o allexport; \
 	source .env; \
 	set +o allexport; \
 	${REPO_BASE_DIR}/scripts/docker-compose-config.bash -e .env $< docker-compose.aws.yml > $@
 
 .PHONY: ${TEMP_COMPOSE}-dalco
-${TEMP_COMPOSE}-dalco: dyn_cfg.yml docker-compose.yml docker-compose.dalco.yml .env
+${TEMP_COMPOSE}-dalco: traefik_dynamic_config.yml docker-compose.yml docker-compose.dalco.yml .env
 	@set -o allexport; \
 	source .env; \
 	set +o allexport; \
 	${REPO_BASE_DIR}/scripts/docker-compose-config.bash -e .env $< docker-compose.dalco.yml > $@
 
 .PHONY: ${TEMP_COMPOSE}-public
-${TEMP_COMPOSE}-public: dyn_cfg.yml docker-compose.yml docker-compose.public.yml .env
+${TEMP_COMPOSE}-public: traefik_dynamic_config.yml docker-compose.yml docker-compose.public.yml .env
 	@set -o allexport; \
 	source .env; \
 	set +o allexport; \
 	${REPO_BASE_DIR}/scripts/docker-compose-config.bash -e .env $< docker-compose.public.yml > $@
 
 .PHONY: ${TEMP_COMPOSE}-master
-${TEMP_COMPOSE}-master: dyn_cfg.yml docker-compose.yml docker-compose.master.yml .env
+${TEMP_COMPOSE}-master: traefik_dynamic_config.yml docker-compose.yml docker-compose.master.yml .env
 	@set -o allexport; \
 	source .env; \
 	set +o allexport; \
