move grafana dashboards to ./osparc-config

diff --git a/services/monitoring/Makefile b/services/monitoring/Makefile
--- a/services/monitoring/Makefile
+++ b/services/monitoring/Makefile
@@ -108,7 +108,7 @@ grafana-export: ## Export grafana dashboards and datasources
 	python3 export.py;
 
 .PHONY: grafana-import
-grafana-import: ## Import grafana dashboards and datasources
+grafana-import: grafana/assets # Import grafana dashboards and datasources
 	@cd grafana/scripts;\
 	if [ ! -d ".venv" ]; \
 	then\
@@ -171,3 +171,25 @@ pgsql_query_exporter_config.yaml: pgsql_query_exporter_config.yaml.j2 ${REPO_CON
 
 smokeping_prober_config.yaml: smokeping_prober_config.yaml.j2 ${REPO_CONFIG_LOCATION} .env .venv
 	$(call jinja, $<, $@);
+
+.PHONY: grafana/assets
+grafana/assets: .config.dir .shared_config.dir
+	$(eval CONFIG_DIR=$(shell cat $(REPO_BASE_DIR)/.config.dir))
+	$(eval SHARED_CONFIG_DIR=$(shell cat $(REPO_BASE_DIR)/.shared_config.dir))
+
+	$(eval GRAFANA_ASSETS_DIR=$(CONFIG_DIR)/assets/grafana)
+	@if [ ! -d $(GRAFANA_ASSETS_DIR) ]; then \
+		echo "Error: folder does not exist $(GRAFANA_ASSETS_DIR)" >&2; \
+		exit 1; \
+	fi
+
+	$(eval GRAFANA_COMMON_ASSETS_DIR=$(SHARED_CONFIG_DIR)/assets/grafana)
+	@if [ ! -d $(GRAFANA_COMMON_ASSETS_DIR) ]; then \
+		echo "Error: folder does not exist $(GRAFANA_COMMON_ASSETS_DIR)" >&2; \
+		exit 1; \
+	fi
+
+	@rm -rf $(REPO_BASE_DIR)/services/monitoring/grafana/assets || true
+	@mkdir -p $(REPO_BASE_DIR)/services/monitoring/grafana/assets
+	@cp -r $(GRAFANA_ASSETS_DIR)/* $(REPO_BASE_DIR)/services/monitoring/grafana/assets
+	@cp -r $(GRAFANA_COMMON_ASSETS_DIR) $(REPO_BASE_DIR)/services/monitoring/grafana/assets/shared
